window.$DEVC = {
  "splunkWebUrl": "http://localhost:8000",
  "splunkdHostUrl": "https://localhost:8089",
  "adminToken": "eyJraWQiOiJzcGx1bmsuc2VjcmV0IiwiYWxnIjoiSFM1MTIiLCJ2ZXIiOiJ2MiIsInR0eXAiOiJzdGF0aWMifQ.eyJpc3MiOiJhZG1pbiBmcm9tIExJVFRMRVJFRCIsInN1YiI6ImFkbWluIiwiYXVkIjoic3BsdW5rdGVzdCIsImlkcCI6IlNwbHVuayIsImp0aSI6IjY1OWQ4NDljNzYxMmFlZmEzZGRiNGE1NmViNmNhMDUxMWMwOGI4MzBhYTFkZGNlY2RkZDFkZjNjYjU1YWEzODUiLCJpYXQiOjE2Nzc1OTcxNTYsImV4cCI6MTY4Mjc3NzU1NiwibmJyIjoxNjc3NTk3MTU2fQ.6Z-_qAAhru88IvhFpPjSImuBjTwhetwsS0Pg14eIqWAWWWOayigb2TMR1zENJNapAqdOAxJH1nEPheix25_bNQ"
}
