name: Radware CWAF Enrichment SplunkApp Frontend Testing
run-name: ${{ github.ref_name }} Test SplunkApp Frontend
on:
  push:
    branches:
      - seleniumtesting
jobs:
  buildbase:
    uses: './.github/workflows/base-build-install.yml'
  Test-SplunkApp-Frontend:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start Docker Container
        shell: pwsh
        run: |
          Invoke-Build -Task TestFrontendInDocker
      - name: test frontend
        id: test_frontend
        uses: zyborg/pester-tests-report@v1
        with:
          test_results_path: output/TestResults_Frontend.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}