name: Radware CWAF Enrichment SplunkApp Testing
run-name: ${{ github.ref_name }} Test SplunkApp Rest Endpoints
on:
  push:
    branches:
      - seleniumtesting
jobs:
  start-full-test:
    uses: ./.github/workflows/base-testing.yml
    with:
      run_frontend: true
    secrets: inherit
    permissions: write-all