name: Radware CWAF Enrichment SplunkApp Testing
run-name: ${{ github.ref_name }} Integration Testing SplunkApp ${{ github.run_number }}
on:
  push:
    branches:
      - master
jobs:
  start-full-test:
    uses: ./.github/workflows/base-testing.yml
    with:
      run_frontend: true
    secrets: inherit
    permissions: write-all
